version: 0.0
os: linux

files:
  - source: .
    destination: /home/ec2-user/my-node-app
    permissions:
      - object: install_npm_packages.sh
        pattern: 755
      - object: start_pm2_service.sh
        pattern: 755

hooks:
  AfterInstall:
    - location: /install_npm_packages.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: /start_pm2_service.sh
      timeout: 300
      runas: root
