version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16 
    commands:
      - echo Installing Mocha...
      - npm install -g mocha
      - echo Installing PM2...
      - npm install -g pm2

  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install unit.js

  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      #- mocha test.js

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Starting Node.js services with PM2...
      - pm2 start app.js --name "my-node-app"

artifacts:
  files:
    - app.js
    - index.html
    - package.json
    - node_modules/async/*
    - node_modules/lodash/*
    - appspec.yml
    - install_npm_packages.sh
    - start_pm2_service.sh
